spring:
#  mvc:
#    hidden method:
#      filter:
#        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: My@newPassword1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8068
