drop table if exists pay_fact cascade;

drop table if exists my_user cascade;

drop table if exists product_using_user cascade;

drop table if exists product_using cascade;

drop table if exists my_check cascade;

drop table if exists temp_user cascade;

drop table if exists my_session cascade;

CREATE TABLE IF NOT EXISTS my_session
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(255),
    date      DATE,
    admin_Id  BIGINT,
    is_closed BOOLEAN
);

CREATE TABLE IF NOT EXISTS temp_user
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname VARCHAR(255),
    lastname  VARCHAR(255),
    session_id BIGINT,
    CONSTRAINT fk_member_list FOREIGN KEY (session_id) REFERENCES my_session(id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS pay_fact
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_data  BIGINT,
    amount     DOUBLE PRECISION,
    CONSTRAINT fk_user_data FOREIGN KEY (user_data) REFERENCES temp_user (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS my_check
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT,
    pay_fact    BIGINT,
    name       VARCHAR(255),
    CONSTRAINT fk_session_id FOREIGN KEY (session_id) REFERENCES my_session (id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_fact FOREIGN KEY (pay_fact) REFERENCES pay_fact (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product_using
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    check_id     BIGINT,
    product_name VARCHAR(255),
    cost         DOUBLE PRECISION,
    CONSTRAINT fk_check FOREIGN KEY (check_id) REFERENCES my_check (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS my_user
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname VARCHAR(255),
    lastname  VARCHAR(255),
    session_id BIGINT,
    CONSTRAINT fk_member_list FOREIGN KEY (session_id) REFERENCES my_session(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS product_using_user
(
    user_id          BIGINT,
    product_using_id BIGINT,
    CONSTRAINT fk_product_using FOREIGN KEY (product_using_id) REFERENCES product_using (id) ON DELETE CASCADE,
    CONSTRAINT fk_user          FOREIGN KEY (user_id) REFERENCES temp_user (id) ON DELETE CASCADE,
    CONSTRAINT pk_product_using_users PRIMARY KEY (product_using_id, user_id)
);

-- insert into my_user (firstname,lastname) VALUES ('Alex','Starikov');
-- insert into my_user (firstname,lastname) VALUES ('Anton','Takhayev');
-- insert into my_user (firstname,lastname) VALUES ('Andrew','Tkachenko');
-- insert into my_user (firstname,lastname) VALUES ('Artem','Zhukov');
-- insert into my_user (firstname,lastname) VALUES ('Ruslan','Zelentcov');

